name: Fuzzing Campaign
on: [push, pull_request]

jobs:

  # Compile and fuzz job
  build-and-fuzz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest

    - name: Run Fuzzing Campaign
      run: |
            docker run -d --name fuzzing-container ghcr.io/${{ github.repository }}:latest
            sleep 3000 # Wait for 50 minutes
            docker stop fuzzing-container
            docker cp fuzzing-container:/output ./fuzzing-results

    - name: Compress fuzzing results
      run: |
        tar -czvf fuzzing-results.tar.gz ./fuzzing-results

    - name: Upload compressed fuzzing results
      uses: actions/upload-artifact@v2
      with:
        name: fuzzing-results
        path: ./fuzzing-results.tar.gz